
```{r Setup}
# Install packages and read in data
#install.packages("tidyverse")
library(tidyverse)
library(ggplot2)
data <- read.csv("Uncleaned_DS_jobs.csv")
# Prevents Scientific Notation 
options(scipen = 100)

view(data)
summary(data)
```

```{r EDA}
# First we are going to start of by doing a little EDA (some of these graphs are more helpful than others)
ggplot(data, aes(x=Salary.Estimate)) + geom_bar(stat="count", color='black', fill='blue')+ theme(axis.text.x = element_text(lineheight = 0.5, angle = 90, vjust = 0.5, hjust=1))
```

```{r EDA}
# Lots of values at 0 (they weren't provided)
ggplot(data, aes(x=Founded)) + geom_bar(stat="count", color='black', fill='blue')
```
```{r EDA}
# Lots of negative reviews (-1's), which is likely an error
ggplot(data, aes(x=Rating)) + geom_bar(stat="count", color='black', fill='blue')
```
```{r EDA}
# City isn't very helpful to see visually (too many unique cities)
data[c('City', 'State')] <- str_split_fixed(data$Location, ', ', 2)
#ggplot(data, aes(x=City)) + geom_bar(stat="count", color='black', fill='blue')+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
ggplot(data, aes(x=State)) + geom_bar(stat="count", color='black', fill='blue')+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```
```{r EDA}
ggplot(data, aes(x=Size)) + geom_bar(stat="count", color='black', fill='blue')+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```
```{r EDA}
ggplot(data, aes(x=Type.of.ownership)) + geom_bar(stat="count", color='black', fill='blue')+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```
```{r EDA}
# Lots of negative values in all of these plots (definitely just placeholder values)
ggplot(data, aes(x=Industry)) + geom_bar(stat="count", color='black', fill='blue')+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```
```{r EDA}
# More negative values here and some unknown
ggplot(data, aes(x=Sector)) + geom_bar(stat="count", color='black', fill='blue')+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```

```{r Cleaning}
# Remove -1's from all columns (can't have negative values for any of these)
data[] <- lapply(data, gsub, pattern = "-1", replacement = NA, fixed = TRUE)

#view(data)
```

```{r Cleaning Salary Estimate}
# We are converting the salary estimates to numeric values
# List of things to remove from column
vec1 <- c("\\(Employer" = "","K" = "000","\\$" = "")
# Split data
data[c('Salary', 'Remove')] <- str_split_fixed(data$Salary.Estimate, ' ', 2)
# Replace unwanted string with nothing
data$Salary <- str_replace_all(data$Salary, vec1)
# Split into min and max salaries
data[c('MinSalary', 'MaxSalary')] <- as.numeric(str_split_fixed(data$Salary, '-', 2)) 
# Find Average Salary
data$AvgSalary <- rowMeans(data[20:21], na.rm=TRUE)


#view(data)
#summary(data)
```

```{r Cleaning Revenue}
# Now we will do the same with Revenue and a few other columns
vec2 <- c("Unknown / Non-Applicable" = NA,"\\$" = "","\\+" = "","\\(USD\\)" = "")
data$Revenue <- str_replace_all(data$Revenue, vec2)
data[c('MinRevenue', 'MaxRevenue')] <- str_split_fixed(data$Revenue, 'to', 2)
# Check and replace only in MinRevenue for billion/million 
vec3 <- c(" billion" = "000000000"," million" = "000000")
data$MinRevenue <- as.numeric(str_replace_all(data$MinRevenue, vec3))
# Check MaxRevenue for million/billion and update MinRevenue accordingly
data <- data %>% 
   mutate(MinRevenue = ifelse(grepl('million', data$MaxRevenue), MinRevenue*1000000, MinRevenue))
data <- data %>% 
   mutate(MinRevenue = ifelse(grepl('billion', data$MaxRevenue), MinRevenue*1000000000, MinRevenue))
# Check and replace only in MaxRevenue for billion/million 
data$MaxRevenue <- as.numeric(str_replace_all(data$MaxRevenue, vec3))
data$AvgRevenue <- rowMeans(data[23:24], na.rm=TRUE)

#view(data)
#summary(data)
```

```{r Cleaning Company Employee Count}
# Cleaning Company Employee Count
vec3 <- c("employees" = "","\\+" = "")
data$Size <- str_replace_all(data$Size, vec3)
data[c('MinEmployeeCount', 'MaxEmployeeCount')] <- as.numeric(str_split_fixed(data$Size, 'to', 2))
data$AvgEmployeeCount <- ceiling(rowMeans(data[26:27], na.rm=TRUE))


#view(data)
#summary(data)
```

```{r Cleaning Job Description (Scrape Skills and Store as Dummy Variables)}
# We are only going to take the following: Python, SAS, MATLAB, R, Java, SQL
data$Python <- ifelse(str_extract(data$Job.Description, "Python") %in% "Python",1,0)
data$SAS <- ifelse(str_extract(data$Job.Description, "SAS") %in% "SAS",1,0)
data$MATLAB <- ifelse(str_extract(data$Job.Description, "MATLAB") %in% "MATLAB",1,0)
data$R <- ifelse(str_extract(data$Job.Description, " R ") %in% " R ",1,0)
data$Java <- ifelse(str_extract(data$Job.Description, "Java") %in% "Java",1,0)
data$SQL <- ifelse(str_extract(data$Job.Description, "SQL") %in% "SQL",1,0)

view(data)
```

```{r Cleaning}
# Delete unwanted columns
data <- data[-c(4,19)]
# Convert Rating to Numeric
data$Rating <- as.numeric(data$Rating)
```

```{r Cleaning}
# Convert all empty values to NA 
data[data == ""] <- NA
# Check for NA values
sum(is.na(data))
# Function to replace all numeric na values with the median
for(i in which(sapply(data, is.numeric))){
  data[is.na(data[,i]),i] <- median(data[,i], na.rm = TRUE)}
# Convert remaining Categorical NA values to Not Provided 
data[is.na(data) == TRUE] <- "Not Provided"

view(data)
summary(data)
```

```{r Create CSV} 
write.csv(data,"Cleaned_Data.csv", row.names=TRUE)
```

```{r Visualizations}
par(mfrow=c(3,1))
ggplot( data, aes(x=AvgSalary)) + geom_histogram(bins=10, color='black', fill='blue')
ggplot( data, aes(x=MaxSalary)) + geom_histogram(bins=10, color='black', fill='green')
ggplot( data, aes(x=MinSalary)) + geom_histogram(bins=10, color='black', fill='red')
```

```{r Visualizations}
par(mfrow=c(3,1))
ggplot( data, aes(x=AvgEmployeeCount)) + geom_histogram(bins=6, color='black', fill='blue')
ggplot( data, aes(x=MaxEmployeeCount)) + geom_histogram(bins=6, color='black', fill='green')
ggplot( data, aes(x=MinEmployeeCount)) + geom_histogram(bins=6, color='black', fill='red')
```

```{r Visualizations}
ggplot( data, aes(x=Rating)) + geom_histogram(bins=10, color='black', fill='blue')
```
```{r Visualizations}
par(mfrow=c(3,1))
ggplot( data, aes(x=AvgRevenue)) + geom_histogram(bins=10, color='black', fill='blue')
ggplot( data, aes(x=MinRevenue)) + geom_histogram(bins=10, color='black', fill='red')
ggplot( data, aes(x=MaxRevenue)) + geom_histogram(bins=10, color='black', fill='green')
```

```{r Visualizations}
par(mfrow=c(3,1))
ggplot( data, aes(y=AvgSalary)) + geom_boxplot(color='black', fill='blue',notch=FALSE)
ggplot( data, aes(y=MinSalary)) + geom_boxplot( color='black', fill='red',notch=FALSE)
ggplot( data, aes(y=MaxSalary)) + geom_boxplot( color='black', fill='green',notch=FALSE)
```

```{r Visualizations}
# Lets also look at some of these graphs again now that we cleaned out the data set
par(mfrow=c(3,2))
ggplot(data, aes(x=State)) + geom_bar(stat="count", color='black', fill='blue')+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
ggplot(data, aes(x=Type.of.ownership)) + geom_bar(stat="count", color='black', fill='blue')+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
ggplot(data, aes(x=Sector)) + geom_bar(stat="count", color='black', fill='blue')+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
ggplot(data, aes(x=Sector)) + geom_bar(stat="count", color='black', fill='blue')+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
ggplot(data, aes(x=Industry)) + geom_bar(stat="count", color='black', fill='blue')+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
ggplot(data, aes(x=Founded)) + geom_bar(stat="count", color='black', fill='blue')+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
ggplot(data, aes(x=Rating)) + geom_bar(stat="count", color='black', fill='blue')
```








